name: CI

on: [push, pull_request]

jobs:
  perl-job:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - '5.30'
          - '5.32'
#          - 'latest'
    container:
      image: perl:${{ matrix.perl-version }}
    name: Perl ${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Perl version
        run: |
            perl -v

      - name: Test
        run: |
            prove
